resources/routes.py
import json
import logging
from typing import Optional

import requests
from flask import redirect, render_template, request, url_for
from flask_jwt_extended import get_jwt, jwt_required, verify_jwt_in_request
from flask_smorest import Blueprint

from resources.auth import TokenManager
from resources.course import CourseList
from resources.course_register import CourseRegisterList, RegistersInStudent, RegistersInTutor
from resources.student import Student, StudentList
from resources.tutor import Tutor, TutorList

blp = Blueprint("Routes", __name__, description="html operations")

logger = logging.getLogger(__name__)


@blp.route("/")
def root():
    """Redirects users to /homepage"""
    return redirect(url_for("Routes.homepage"))


@blp.route("/homepage")
def homepage():
    """
    Handles the displayed homepage logic; gets the current and populates. If there is a jwt token the user will
    be retrieved and their information populated on the login page.
    """
    user = None
    jwt = verify_jwt_in_request(optional=True)
    if jwt:
        payload = get_jwt()
        id = payload["sub"]
        if payload["user_type"] == "tutor":
            user = Tutor.get(id).json

        elif payload["user_type"] == "student":
            user = Student.get(id).json

    # populate sections with data
    tutors = TutorList.get().json
    courses = CourseList.get().json
    students = StudentList.get().json
    events = CourseRegisterList.get().json

    return render_template("homepage.html", user=user, tutors=tutors, events=events, students=students, courses=courses)


@blp.route("/login")
def login():
    """Actions the request to login, redirects user to the login form."""
    jwt = verify_jwt_in_request(optional=True)
    if jwt:
        return homepage()

    return render_template("login_form.html")


@blp.route("/logout")
@jwt_required(locations=["cookies"])
def logout():
    requests.post(f"{request.url_root}{url_for('Auth.Logout')}")
    deauthed_response = TokenManager.unset_jwt()

    return deauthed_response


@blp.post("/handle_login")
def handle_login():
    """
    Handles the login e.g. student or tutor, if success we redirect to the homepage with a logged in state
    else we regenerate the login form to try again.
    """
    response = None
    user_type = request.form["user_type"]
    payload = _convert_form_to_json_payload(request.form, ["user_type"])
    if user_type == "tutor":
        response = requests.post(f"{request.url_root}{url_for('Auth.TutorLogin')}", data=payload)

    elif user_type == "student":
        response = requests.post(f"{request.url_root}{url_for('Auth.StudentLogin')}", data=payload)

    if response.status_code == 200:
        authed_response = TokenManager.generate_response(
            response.json()["access_token"], response.json()["refresh_token"]
        )
        return authed_response

    return redirect(url_for("Routes.login"))


@blp.route("/user_info")
def user_info():
    """Renders the users information such that a user can login, if not logged in it redirects to the login form."""
    user = None
    jwt = verify_jwt_in_request(optional=True)
    if jwt:
        payload = get_jwt()
        uid = payload["sub"]
        if payload["user_type"] == "tutor":
            user = Tutor.get(uid).json

        elif payload["user_type"] == "student":
            user = Student.get(uid).json

        return render_template("user_info.html", user=user, user_type=payload["user_type"])

    return render_template("login_form.html")


def _convert_form_to_json_payload(form: dict, exclude: Optional[list] = None):
    """Helper method to convert form to a raw json data payload"""
    as_dict = dict(form)
    if exclude:
        for item in exclude:
            as_dict.pop(item)
        return as_dict

    return as_dict


@blp.post("/handle_update")
@jwt_required(locations=["cookies"])
def user_update():
    """Handles the submission from the /user_info endpoint."""
    user_payload = get_jwt()
    uid = user_payload["sub"]
    form_payload = _convert_form_to_json_payload(request.form)
    if user_payload["user_type"] == "tutor":
        response = Tutor.put(tutor_id=uid, tutor_data=form_payload)

    elif user_payload["user_type"] == "student":
        response = Student.put(student_id=uid, student_data=form_payload)

    if response.status_code in [200, 201]:
        return redirect(url_for("Routes.homepage", user=response.json))

    return redirect(url_for("Routes.user_info"))


@blp.route("/signup")
def signup():
    """Renders a register form such that a user can sign up."""
    jwt = verify_jwt_in_request(optional=True)
    if jwt:
        return homepage()

    return render_template("register_form.html")


@blp.post("/handle_signup")
def handle_signup():
    """Handles the response from a register form and actions the appropriate endpoints, if the signup responds with a
    success then the user is redirected to the login page, otherwise the user is redirected to signup again."""
    response = None

    user_type = request.form["user_type"]
    print(request.files)
    payload = _convert_form_to_json_payload(request.form, ["user_type", "profile_picture"])
    # FIXME: file upload no not currently working
    # file_upload = None
    # file_payload = {"profile_picture": request.files, "user_type": user_type}

    if user_type == "student":
        response = requests.post(f"{request.url_root}{url_for('Students.StudentList')}", data=payload)

    elif user_type == "tutor":
        response = requests.post(f"{request.url_root}{url_for('Tutors.TutorList')}", data=payload)

    if response and response.status_code == 201:
        return redirect(url_for("Routes.login"))

    return render_template("register_form.html")


@blp.route("/list_fields/<string:type>", methods=["GET", "POST"])
def list_fields(type):
    """
    A generic form that can list the contents of any table in the database or from another endpoint.
    Databases:
    Tutors, Students, Subjects, Courses,

    Endpoints:
    /my_people
    /my_courses
    """
    fields = None
    if type == "tutor":
        fields = TutorList.get().json

    elif type == "course":
        fields = CourseList.get().json

    elif type == "student":
        fields = StudentList.get().json

    else:
        fields = CourseRegisterList.get().json

    if fields is None:
        redirect(url_for("Routes.homepage"))

    return render_template("list.html", fields=fields, type=type)


@blp.route("/detail", methods=["GET", "POST"])
def detail():
    """Used on click to display summary information on a user"""
    args = request.args
    return render_template("detail.html", name=args["name"], summary=args.get("summary"), type=args["type"])


@blp.get("/my_people")
@jwt_required(locations=["cookies"])
def my_people():
    """protected, uses jwt token to check what type of user is calling this method
    :returns
        students if the user is a `tutor`
        tutors if the user is a `student`
    """
    response = None
    type = None
    # FIXME: register ids not currently used
    # register_ids = []
    jwt_payload = get_jwt()
    uid = jwt_payload["sub"]
    if jwt_payload["user_type"] == "student":
        type = "My Tutors"
        response = RegistersInStudent.get(student_id=uid)

    elif jwt_payload["user_type"] == "tutor":
        type = "My Students"
        response = RegistersInTutor.get(tutor_id=uid)

    if response and response.status_code == 200:
        # TODO: implement this properly in the backend to remove this horrible logic
        desired_fields = []
        for raw_json in response.response:
            json_data = json.loads(raw_json)
            for json_item in json_data:
                if jwt_payload["user_type"] == "tutor":
                    desired_fields.append(json_item.get("students"))
                elif jwt_payload["user_type"] == "student":
                    desired_fields.append(json_item.get("tutors"))

        flat_list = [item for sublist in desired_fields for item in sublist]
        return render_template("list.html", fields=flat_list, type=type)

    return redirect(url_for("Routes.homepage"))


@blp.get("/my_courses")
@jwt_required(locations=["cookies"])
def my_courses():
    """
    protected, uses jwt token to check what type of user is calling this method
    Returns courses associated with a user
    :returns
        students if the user is a `tutor`
        tutors if the user is a `student`
    """
    response = None
    type = "My Courses"
    # FIXME: register ids not currently used
    # register_ids = []
    jwt_payload = get_jwt()
    uid = jwt_payload["sub"]
    if jwt_payload["user_type"] == "student":
        response = RegistersInStudent.get(student_id=uid)

    elif jwt_payload["user_type"] == "tutor":
        response = RegistersInTutor.get(tutor_id=uid)

    if response and response.status_code == 200:
        # TODO: implement this properly in the backend to remove this horrible logic
        desired_fields = []
        for raw_json in response.response:
            json_data = json.loads(raw_json)
            for json_item in json_data:
                print(json_item)
                desired_fields.append(json_item.get("course"))

        return render_template("list.html", fields=desired_fields, type=type)

    return redirect(url_for("Routes.homepage"))


@blp.post("/delete_account")
@jwt_required(locations=["cookies"])
def delete_account():
    """Used to delete account"""
    raise NotImplementedError(
        "Deletion of accounts is not supported yet, to do this use the API methods in the swagger UI or postman"
    )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tutoring</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <meta name="viewport" context="width=device-width, initial-scale=1.0">
</head>


<body style="min-height: 75rem; padding-top: 4.5rem;">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand">Tutoring website</a>
    </nav>
    {% block content %}

    {% endblock content %}
</body>

templates/detail.html
{% extends "base.html" %}
{% block content %}

<section class="container">
    <div class="card">
        <div class="card-header">
            {{ name }}
            <a class="btn btn-sm, btn-primary float-right" href="{{url_for('Routes.homepage')}}"> Go Back to homepage </a>
        </div>

        <div class="card-body">
            {{ summary }}
        </div>
        <div class="card-footer">
        <a class="btn btn-sm btn-secondary float-left" href="{{url_for('Routes.homepage')}}">Home</a>
        <a class="btn btn-sm btn-secondary float-right" href="{{url_for('Routes.list_fields', type=type)}}">Back to {{ type }}</a></div>
    </div>
</section>
{% endblock content %}

templates/list.html
{% extends "base.html" %}
{% block content %}
<section class="container">
    <div class="card">
        <div class="card-header">
            {{ type }}
            <div class="btn-group float-right">
                <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Action
                </button>
                <div class="dropdown-menu">
{#                    <a class="dropdown-item" href="{{ url_for('form') }}">Write</a>#}
                </div>
            </div>
        </div>
    </div>
</section>
<section class="container">
    <div class="card">
            <div class="card-body">
                <table class="table table-dark">
                    <tr>

                        {% for key, _ in fields[0].items() %}
                        <th>{{ key }}</th>
                        {% endfor %}
                    </tr>
                    {% for field in fields %}
                    <tr>
                        {% for key, value in field.items() %}
                            {% if key == "name" %}
                            <td><a href="{{ url_for('Routes.detail', name=field.name, summary=field.summary, type=type)}}">{{ field.name }}</a></td>
                            {% elif key != "summary"  or key != "profile_picture" %}
                            <td>{{ value }}</td>
                            {% endif %}
                        {% endfor %}
                        <td>
                            <div class="btn-group show">
                                <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-bars"></i>
                                </button>
                                <div class="dropdown-menu">
{#                                    <a class="dropdown-item" href="{{ url_for('form', uid=movie.uid) }}">Update</a>#}
{#                                    <a class="dropdown-item" href="{{ url_for('delete', uid=movie.uid)}}">Delete</a>#}
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="card-footer">
            <a class="btn btn-sm btn-secondary float-left" href="{{url_for('Routes.homepage')}}">Home</a>
            </div>
    </div>
</section>
{% endblock content %}

templates/login_form.html
{% extends "base.html" %}
{% block content %}
  <div class="tabs">
    <div role="tablist">
      <button id="tab-1" aria-selected="true" aria-controls="tab-panel-1" role="tab" type="button" tabindex="0">
        Student
      </button>
      <button id="tab-2" aria-selected="false" aria-controls="tab-panel-2" role="tab" type="button" tabindex="-1">
        Tutor
      </button>
    </div>
    <div id="tab-panel-1" aria-labelledby="tab-1" role="tabpanel" tabindex="0">

        <div class="card">
        <form action="/handle_login" method="POST" name="form">
        <div class="card-header">
            Student Login
        </div>

        <div class="card-body">

        <div class="form-group">
            <label for="title">Username</label>
            <input type="text" class="form-control" value="" placeholder="username" name="username">
            <label class="login-field-icon fui-user" for="login-name"></label>
        </div>

        <div class="form-group">
            <label for="title">Password</label>
            <input type="password" class="form-control" value="" placeholder="password" name="password">
            <label class="login-field-icon fui-lock" for="login-pass"></label>
        </div>

        <input type="hidden" name="user_type" id="user_type" value="student" />
        </div>

        <div class="card-footer">
        <input type="submit" value="Log in" class="btn btn-sm btn-primary float-right">
        <a class="btn btn-sm btn-secondary float-left" href="{{url_for('Routes.homepage', user=user)}}">Cancel</a>
        <a class="btn btn-sm btn-secondary float-right" href="{{url_for('Routes.signup')}}">Signup</a>
        </div>
        </form>

        </div>

    </div>

    <div id="tab-panel-2" aria-labelledby="tab-2" role="tabpanel" tabindex="-1" hidden>

        <div class="card">
        <form action="/handle_login" method="POST" name="form">
        <div class="card-header">
            Tutor Login
        </div>

        <div class="card-body">

        <div class="form-group">
            <label for="title">Username</label>
            <input type="text" class="form-control" value="" placeholder="username" name="username">
            <label class="login-field-icon fui-user" for="login-name"></label>
        </div>

        <div class="form-group">
            <label for="title">Password</label>
            <input type="password" class="form-control" value="" placeholder="password" name="password">
            <label class="login-field-icon fui-lock" for="login-pass"></label>
        </div>

        <input type="hidden" name="user_type" id="user_type" value="tutor" />
        </div>

        <div class="card-footer">
        <input type="submit" value="Log in" class="btn btn-sm btn-primary float-right">
        <a class="btn btn-sm btn-secondary float-left" href="{{url_for('Routes.homepage')}}">Cancel</a>
        <a class="btn btn-sm btn-secondary float-right" href="{{url_for('Routes.signup')}}">Signup</a>
        </div>
        </form>

        </div>

    </div>
  </div>
    <script>
    const tabElements = document.querySelectorAll('button[role="tab"]');
const panelElements = document.querySelectorAll('[role="tabpanel"]');
let activeIndex = 0;

// Listen to clicks and key presses on tabs
tabElements.forEach(function (tab, index) {
  tab.addEventListener("click", function (event) {
    setActiveTab(index);
  });

  tab.addEventListener("keydown", function (event) {
    const lastIndex = tabElements.length - 1;

    if (event.code === "ArrowLeft" || event.code === "ArrowUp") {
      if (activeIndex === 0) {
        // First element, jump to end
        setActiveTab(lastIndex);
      } else {
        // Move left
        setActiveTab(activeIndex - 1);
      }
    } else if (event.code === "ArrowRight" || event.code === "ArrowDown") {
      if (activeIndex === lastIndex) {
        // Last element, jump to beginning
        setActiveTab(0);
      } else {
        // Move right
        setActiveTab(activeIndex + 1);
      }
    } else if (event.code === "Home") {
      // Move to beginning
      setActiveTab(0);
    } else if (event.code === "End") {
      // Move to end
      setActiveTab(lastIndex);
    }
  });
});

function setActiveTab(index) {
  // Make currently active tab inactive
  tabElements[activeIndex].setAttribute("aria-selected", "false");
  tabElements[activeIndex].tabIndex = -1;

  // Set the new tab as active
  tabElements[index].setAttribute("aria-selected", "true");
  tabElements[index].tabIndex = 0;
  tabElements[index].focus();

  setActivePanel(index);
  activeIndex = index;
}

function setActivePanel(index) {
  // Hide currently active panel
  panelElements[activeIndex].setAttribute("hidden", "");
  panelElements[activeIndex].tabIndex = -1;

  // Show the new active panel
  panelElements[index].removeAttribute("hidden");
  panelElements[index].tabIndex = 0;
}

    </script>
{% endblock content %}

templates/register_form.html
{% extends "base.html" %}
{% block content %}
<div class="tabs">
    <div role="tablist">
      <button id="tab-1" aria-selected="true" aria-controls="tab-panel-1" role="tab" type="button" tabindex="0">
        Student
      </button>
      <button id="tab-2" aria-selected="false" aria-controls="tab-panel-2" role="tab" type="button" tabindex="-1">
        Tutor
      </button>
    </div>
    <div id="tab-panel-1" aria-labelledby="tab-1" role="tabpanel" tabindex="0">

        <div class="card">
        <form action="/handle_signup" method="POST" name="form">
        <div class="card-header">
            Student Signup
        </div>


        <div class="card-body">

        <div class="form-group">

            <label for="title">Username</label>
            <input type="text" class="form-control" value="" placeholder="username" name="username">
            <label class="login-field-icon fui-user" for="login-name"></label>

        </div>

        <div class="form-group">

            <label for="title">Password</label>
            <input type="password" class="form-control" value="" placeholder="password" name="password">
            <label class="login-field-icon fui-lock" for="login-pass"></label>

        </div>

        <div class="form-group">

            <label for="title">Email</label>
            <input type="email" class="form-control" value="" placeholder="example@gmail.com" name="email">
            <label class="login-field-icon fui-lock" for="login-email"></label>

        </div>

        <div class="form-group">

            <label for="title">Name</label>
            <input type="text" class="form-control" value="" placeholder="Jon Doe" name="name">
            <label class="login-field-icon fui-lock" for="login-name"></label>

        </div>

        <div class="form-group">

            <label for="title">age</label>
            <input type="number" class="form-control" value="" placeholder="10" name="age">
            <label class="login-field-icon fui-lock" for="login-age"></label>

        </div>

        <div class="form-group">

            <label for="title">Summary</label>
            <textarea class="form-control" placeholder="Summary" name="summary"></textarea>
            <label class="login-field-icon fui-lock" for="login-summary"></label>

        </div>

        <div class="form-group">

            <label for="title">Profile Picture</label>
            <input type="file" class="form-control-file" name="profile_picture">
            <label class="login-field-icon fui-user" for="login-profile-picture"></label>

        </div>

            <input type="hidden" name="user_type" id="user_type" value="student" />

        </div>

    <div class="card-footer">
        <input type="submit" value="Sign Up" class="btn btn-sm btn-primary float-right">
        <a class="btn btn-sm btn-secondary float-left" href="{{url_for('Routes.homepage')}}">Cancel</a>
        <a class="btn btn-sm btn-secondary float-right" href="{{url_for('Routes.login')}}">login</a>
    </div>

    </form>

    </div>
    </div>


    <div id="tab-panel-2" aria-labelledby="tab-2" role="tabpanel" tabindex="-1" hidden>
     <div class="card">
        <form action="/handle_signup" method="POST" name="form">
        <div class="card-header">
            Tutor Signup
        </div>


        <div class="card-body">

        <div class="form-group">

            <label for="title">Username</label>
            <input type="text" class="form-control" value="" placeholder="username" name="username">
            <label class="login-field-icon fui-user" for="login-name"></label>

        </div>

        <div class="form-group">

            <label for="title">Password</label>
            <input type="password" class="form-control" value="" placeholder="password" name="password">
            <label class="login-field-icon fui-lock" for="login-pass"></label>

        </div>

        <div class="form-group">

            <label for="title">Email</label>
            <input type="email" class="form-control" value="" placeholder="example@gmail.com" name="email">
            <label class="login-field-icon fui-lock" for="login-email"></label>

        </div>

        <div class="form-group">

            <label for="title">Name</label>
            <input type="text" class="form-control" value="" placeholder="Jon Doe" name="name">
            <label class="login-field-icon fui-lock" for="login-name"></label>

        </div>

        <div class="form-group">

            <label for="title">age</label>
            <input type="number" class="form-control" value="" placeholder="10" name="age">
            <label class="login-field-icon fui-lock" for="login-age"></label>

        </div>

        <div class="form-group">

            <label for="title">Summary</label>
            <textarea class="form-control" placeholder="Summary" name="summary"></textarea>
            <label class="login-field-icon fui-lock" for="login-summary"></label>

        </div>

        <div class="form-group">

            <label for="title">Profile Picture</label>
            <input type="file" class="form-control-file" name="profile_picture">
            <label class="login-field-icon fui-user" for="login-profile-picture"></label>

        </div>

            <input type="hidden" name="user_type" id="user_type" value="tutor" />

        </div>

    <div class="card-footer">
        <input type="submit" value="Sign Up" class="btn btn-sm btn-primary float-right">
        <a class="btn btn-sm btn-secondary float-left" href="{{url_for('Routes.homepage', user=user)}}">Cancel</a>
        <a class="btn btn-sm btn-secondary float-right" href="{{url_for('Routes.login')}}">login</a>
    </div>

    </form>

    </div>
    </div>
</div>
    <script>
    const tabElements = document.querySelectorAll('button[role="tab"]');
const panelElements = document.querySelectorAll('[role="tabpanel"]');
let activeIndex = 0;

// Listen to clicks and key presses on tabs
tabElements.forEach(function (tab, index) {
  tab.addEventListener("click", function (event) {
    setActiveTab(index);
  });

  tab.addEventListener("keydown", function (event) {
    const lastIndex = tabElements.length - 1;

    if (event.code === "ArrowLeft" || event.code === "ArrowUp") {
      if (activeIndex === 0) {
        // First element, jump to end
        setActiveTab(lastIndex);
      } else {
        // Move left
        setActiveTab(activeIndex - 1);
      }
    } else if (event.code === "ArrowRight" || event.code === "ArrowDown") {
      if (activeIndex === lastIndex) {
        // Last element, jump to beginning
        setActiveTab(0);
      } else {
        // Move right
        setActiveTab(activeIndex + 1);
      }
    } else if (event.code === "Home") {
      // Move to beginning
      setActiveTab(0);
    } else if (event.code === "End") {
      // Move to end
      setActiveTab(lastIndex);
    }
  });
});

function setActiveTab(index) {
  // Make currently active tab inactive
  tabElements[activeIndex].setAttribute("aria-selected", "false");
  tabElements[activeIndex].tabIndex = -1;

  // Set the new tab as active
  tabElements[index].setAttribute("aria-selected", "true");
  tabElements[index].tabIndex = 0;
  tabElements[index].focus();

  setActivePanel(index);
  activeIndex = index;
}

function setActivePanel(index) {
  // Hide currently active panel
  panelElements[activeIndex].setAttribute("hidden", "");
  panelElements[activeIndex].tabIndex = -1;

  // Show the new active panel
  panelElements[index].removeAttribute("hidden");
  panelElements[index].tabIndex = 0;
}

    </script>
{% endblock content %}

templates/user_info.html
{% extends "base.html" %}
{% block content %}
    <section class="container">
        <div class="card">
        <form method="POST" action="{{url_for('Routes.user_update')}}">
        <div class="card-header">
            {% if user_type == "tutor" %}
            Edit Tutor
            {% else %}
            Edit Student
            {% endif %}
        </div>

        <div class="card-body">
            {%  for key, value in user.items()  %}
                <div class="form-group">
                {% if key == "registers" %}
                    <label for="{{ key }}">{{ key }}</label>
                    {% for register in registers %}
                                <div class="register-header">
                                course {{ register.name }}
                                </div>
                    {% endfor %}
                {% elif key == "id" or key == "username" %}
                    <label for="{{ key }}">{{ key }}</label>
                    <input class="form-control" type="text" value="{{ value }}" aria-label="readonly input example" readonly>
                {% elif key == "summary" %}
                    <label for="{{ key }}">{{ key }}</label>
                    <textarea class="form-control" id="{{ key }}" name="{{ key }}" rows="10">{{ value }}</textarea>
                {% else %}
                    <label for="{{ key }}">{{ key }}</label>
                <input type="text" class="form-control" id="{{ key }}" name="{{ key }}" value="{{ value }}">
                {% endif %}

                </div>
            {%  endfor %}
        </div>
        <div class="card-footer">
            <a class="btn btn-sm, btn-secondary float-left" href="{{url_for('Routes.homepage')}}">Cancel</a>
            <input class="btn btn-sm, btn-secondary float-right" type="submit" id="submit" value="Save">
        </div>
    </form>
    </div>



    </section>
{% endblock content %}